#! /bin/bash
hostnames=(ec2-52-90-80-45.compute-1.amazonaws.com
ec2-54-183-23-203.us-west-1.compute.amazonaws.com
ec2-54-70-111-57.us-west-2.compute.amazonaws.com
ec2-52-215-87-82.eu-west-1.compute.amazonaws.com
ec2-52-28-249-79.eu-central-1.compute.amazonaws.com
ec2-54-169-10-54.ap-southeast-1.compute.amazonaws.com
ec2-52-62-198-57.ap-southeast-2.compute.amazonaws.com
ec2-52-192-64-163.ap-northeast-1.compute.amazonaws.com
ec2-54-233-152-60.sa-east-1.compute.amazonaws.com)

while getopts "p:o:u:n:i:" arg
do
    case $arg in
        p) # Port
            # echo "port:$OPTARG"
            ;;
        o) # Origin server
            # echo "origin:$OPTARG"
            ;;
        u) # username
            username=$OPTARG
            # echo "username:$OPTARG"
            ;;
        n) # CDN-specific name
            # echo "name:$OPTARG"
            ;;
        i) #private key
            keyfile=$OPTARG
            # echo "keyfile:$OPTARG"
            ;;
        ?)
            echo "unkonw argument"
        exit 1
        ;;
        esac
done

for host in "${hostnames[@]}"
do
    echo 'Close ' $host
    ssh -i $keyfile $username@$host 'killall python'
done

dnsserver=cs5700cdnproject.ccs.neu.edu
echo "Close " $dnsserver
# ssh -i $keyfile manu11@$dnsserver 'killall python'
ssh -i $keyfile $username@$dnsserver 'killall python'
